### ISSUE TITLE
Feedback for Meizu page

### ISSUE THREAD

**Issue by zuibunan** [urbandroid-team/dont-kill-my-app#105]
Meizu 16s Pro
Android 9
Flyme 7.3.4.0A
Version: 20190819

The system doesn't kill my app，but it seems that sleep android can not get accelerometer data after the screen locked

![image](https://user-images.githubusercontent.com/3386786/64309144-2efc2580-cfce-11e9-91c8-216ba1881831.png)

**Comment by petrnalevka** [comment]
Did not see tyhis issue since Android 1.6 - 2.3 when the screen needed to be on tio allow sensor to work.. luckily nowadays Android can run sensors in the background.. hard to say why Flyme is doing this.. anyway you can go to settings > Sleep tracking > Screen dimming > Always on clock.. this will keep your screen on all time during tracking - of course battery consumption will be higher, it would be interesting to see if this fixes the issue..
