### ISSUE TITLE
Add GitHub releases so we can watch them and get updated

### ISSUE THREAD

**Issue by LouisCAD** [urbandroid-team/dont-kill-my-app#26]
Hi, thanks for your project!
Since that state of app killers is likely to change, your repo is likely to change too.
Consequently, it'd be nice to have some semantic versioning available [there](https://github.com/urbandroid-team/dont-kill-my-app/releases) so we can watch it with GitHub's new watch releases feature.

**Comment by Artaud** [comment]
Good idea! Any pointers on where to draw the line between releases?

**Comment by LouisCAD** [comment]
Each time there's a new discovery, or an update from the OEM (bad or good).

You can name the updates by year plus quarter plus update number in the
quarter (e.g. 2019.1.2 if it's the second release of 2019's Q1), like
JetBrains does for its IDEs, so we know how fresh or stale is the update
without having to research or think too much.

**Comment by Artaud** [comment]
We've thought this through and concluded that this would just add a layer of uncertainty. There is no distinct line between a new discovery and a change to an existing one (which happens all the time with new updates of the firmwares), and also lots of times the discoveries aren't confirmed yet but deserve to be published.

I assume that the underlying desire is to stay on top of the information, but github releases wouldn't really help with that since you would have to wade through all the commits from the previous release to the new one to truly see what's been changed.

What is the use case however? The main use case of the site should be to be linked by the developers in their apps or FAQs (or creating your own version using the API) so the users will take a look at the most updated version whenever they face any related issue.
With such use, there would be actually no need for you to stay up to date personally...

**Comment by Mikaela** [comment]
Would https://github.com/urbandroid-team/dont-kill-my-app/commits/master.atom be of any help?
