### ISSUE TITLE
Where can I get information for a vendor?

### ISSUE THREAD

**Issue by ThatWeirdAndrew** [urbandroid-team/dont-kill-my-app#28]
I have an ASUS phone and I would like to add it to the list. How can I get data to see what rating to give them?

**Comment by Artaud** [comment]
Hi! The rating is based on our as developers' experience with complaints from end-users. We as Urbandroid Team don't have many complaints from ASUS users but that's probably partially because ASUS phones have small market share.

Theory aside, you don't have to fill in the rating actually and it will work just fine. Just intuitively, what rating would you give, based on your experience?

**Comment by ThatWeirdAndrew** [comment]
I'd give it a 3/5. There is an optimization app pre-installed with some modifications made by default, eg. blocking apps from starting and killing background tasks when your screen turns off. However, if you know how, you can easily disable these.

**Comment by Artaud** [comment]
I'll reopen this since ASUS isn't added yet, just to have it as a TODO list item in the issues if you don't mind...

**Comment by Artaud** [comment]
@ThatWeirdAndrew could you please make a few screenshots of the optimization app?

**Comment by ThatWeirdAndrew** [comment]
Here is a link to the screenshots: https://imgur.com/a/92k6vPC

The auto deny apps from auto-starting checkbox is checked by default

**Comment by petrnalevka** [comment]
Hello, big thanks I did prepare an Asus entry for DKMA based on your feedback. Please check:

https://dontkillmyapp.com/asus

Please let me know your comments..

**Comment by ThatWeirdAndrew** [comment]
It looks great! Thanks for making this.
