### ISSUE TITLE
Request: Publish the results of the Don't kill my app app

### ISSUE THREAD

**Issue by Xalaxis** [urbandroid-team/dont-kill-my-app#318]
Hi Urbandroid team,

I've had a OnePlus 6 for quite some time now, and always reported having no app sleep issues. Now with the official testing app released I'm getting a clean bill of health (see #30).

Please can you offer the user the option to opt in to statistics reporting, and publish the results on a public dashboard? That way we could all have an accurate way of categorizing OEMs. I think the current ranking is a little biased when it's just based on anecdotal evidence. I'm not saying it's been correct historically, but I think now we might be looking at a situation where it's not updating to the latest evidence.

**Comment by petrnalevka** [comment]
Hello, many thanks.. we are not sure - as OEMs are not themselves transparent about this - but based on observations from 1+ users I think the problem is that 1+ has European and Asian editions with European handling background processing ok but Asian using one of the most brutal app killing. And probably due to issue with supply there is huge number of Asia versions coming to Western markets and causing issues. So I guess you are one of the few lucky 1+ users with a western version - you can double check that from the model number of your phone..

The current scoring is done using this approach https://dontkillmyapp.com/about_score

We reserve the right to apply +1 / -1 to the score based on dev experience. And honestly experience with 1+ was one of the worst.. Our apps have over 3M users and we process around 100 user requests daily and before Samsung released their messed up Android 11 update 1+ accounted for ~50% of all app killing support queries. If you take into consideration their tiny market share, IMHO this really indicate that 1+ did the far worst job on explaining their app killing procedures to their users.

You can check results from the DKMA in this spreadsheet:
https://docs.google.com/spreadsheets/d/1kZFM-C4vgvmFOLFPNg0bNALA_MopVRJDoBudKM1GaxQ/edit?usp=sharing

But I'm afraid using this as a source fro the score is not possible because we have no way of knowing whether the users already change their phone default setup or not..

**Comment by Xalaxis** [comment]
Hi Petr,

Thanks for explaining the score. I understand why you've rated them the way you have now.

These results are really interesting! Does this spreadsheet update in real time?

I tried seeing if I could see any obvious differences between the models in the data, but at the moment there's nothing significant. One thing I'd like to suggest is adding a really simple toggle for "I've made the recommended changes" or "I've not changed any settings" so that we could compare default vs changed states.

![OnePlus 6 success rate by model](https://user-images.githubusercontent.com/12937964/117451850-f64ae700-af3a-11eb-965d-2bebe9a762c9.png)

**Comment by Xalaxis** [comment]
What's strange is that there were people with full success and complete failures on both models, and I don't think that can be explained by just the aggressive battery limiting settings (as they were removed in Android/OxygenOS 10).

**Comment by petrnalevka** [comment]
Hello Matthew, I'm not sure about the toggle, but maybe sending over the number of tests the users performed the benchmark on that device would be an interesting hint maybe? We could than filter for just first time runs and see if people are abel to get to better results with more runs etc..

Anyway why do you think the aggressive battery limiting features have been removed in OxygenOS 10.. do you have any resource your could share about that. I remember 1+ promised to do something about this but nothing really happened? 

Many thanks for doing the chart.. I guess this makes my European vs. Asian theory less plausible..

**Comment by Xalaxis** [comment]
Sorry for the four month delay, life really catches up with you sometimes 😅

I'm afraid I've run out of time to look into this right now, but I hope to pick up this again at some point. Thanks for publishing the results, I'll go ahead and close the issue 🙂👍

>why do you think the aggressive battery limiting features have been removed in OxygenOS 10

Unfortunately this is just anecdotal, but I do believe it to be true. I haven't been able to locate any definitive record of OnePlus changing the settings - not helped by regional differences in execution time I expect.
