### ISSUE TITLE
Feedback for Sony page

### ISSUE THREAD

**Issue by devperson** [urbandroid-team/dont-kill-my-app#320]
Can you also include a guide on how to turn off Stamina mode?

**Comment by mmis1000** [comment]
In practice, it only auto enables when battery is < 15% and not connect to a charger.
And also auto disable itself when you charges the battery over 90(?)%.
At that battery level, do any one still ever bother to run any background service?

Besides that.
If you enabled it manually, you should also know how to disable it.
Because it is the same toggle.
