### ISSUE TITLE
Samsung optimizations vs... 

### ISSUE THREAD

**Issue by d0x360** [urbandroid-team/dont-kill-my-app#391]
So this is more of a question than an issue...

I've disabled everything Samsung related so now I assume there are more things running when they don't need to be.  Would it be beneficial to also download something like greenify (even without root) so things are still being put to sleep but on a more... Accurate cadence?

Thanks.

**Comment by JoshuaGloriod** [comment]
You can actually go in to developer settings and set all the adaptive battery optimizations yourself, manually of course. It's where apps say something like "active". That's the default battery eating state. 

Otherwise yeah, you've turned off Android's power management. This is the only middle ground to be had.

**Comment by d0x360** [comment]
Ahh yes, I actually did that already because I went from one end of the battery spectrum to the other and I was charging the little battery in the flip3 like 3 times a day.

I'm actually going to get rid of it pretty soon.  I was thinking a pixel 6 or p6 pro.  I can (in theory) get the pro for $363 if I trade this in at best buy.  I haven't checked anywhere else.

I just know I gotta get away from Samsung phones.  My first was the Galaxy Nexus which I didn't like because it felt cheap then I didn't like the note 8, 9 or 10+ but I still bought this stupid thing lol.
