### ISSUE TITLE
Nokia disable powersaving instead of uninstall

### ISSUE THREAD

**Issue by lee-tts** [urbandroid-team/dont-kill-my-app#54]
I notice it is possible to disable the com.evenwell.powersaving.g3.xxx app in settings. The instructions on this site do not mention it, but to me it seems like an easier medium-term fix? Is there a reason the instructions don't mention this? Just want to check before I make a pull request. Thanks!

**Comment by petrnalevka** [comment]
Hello, we don't know this. Can you please send a screenshot of the setting screen? Are you sure this is really deactivating the evenwell task killer?

**Comment by Artaud** [comment]
I think that there is some confusion about what app does the evil killing. The app in question is called **Power saver**, and the package name is com.evenwell.powersaving.g3. You are probably talking about com.evenwell.powersaving.g3.overlay.xxx.

It is possible to disable the overlay, but that doesn't help.
It is however **not possible** to disable the Power saver app. As far as I know. I'd love to find out otherwise :0)

Please see a screenshot below from Nokia 6.1

![image](https://user-images.githubusercontent.com/3899990/55388422-884dbd80-5533-11e9-8d76-96ef00a37d97.png)

**Comment by lee-tts** [comment]
Yes, my mistake! Wow, a real noob mistake, too haha. I've now FC'd the right app. Ironically you can also apply background restrictions on battery usage for the Power saver app hahaha. We'll see if it does anything.

**Comment by Artaud** [comment]
That's funny :0)
Unfortunately force close on the Power saver app does not survive reboot, and I think I've seen it wake up from force closed state even without reboot.

**Comment by lee-tts** [comment]
Yes, Power saver does get resurrected without reboot on my Nokia 6 (Pi). Won't be buying more Nokia phones in the future.

**Comment by Artaud** [comment]
I found you can disable the power saver without uninstalling it via this adb command

`adb shell pm disable-user com.evenwell.powersaving.g3`

This makes it possible to enable it later again.
