### ISSUE TITLE
Score representation looks kinda unfair and misleading

### ISSUE THREAD

**Issue by shiarisu** [urbandroid-team/dont-kill-my-app#56]
From a viewpoint of someone who just found your website, I think that the score representation you display using :-1: (thumbsdown) marks seems kinda unfair.
Particularly scores with 1 or 2 :-1:s.
Quoting score definitions from https://dontkillmyapp.com/about_score:
* "Services are killed only when user explicitly configure there phone to do so.."
* "Particular foreground services are killed only when user explicitly configure those services so."

Imho those two are quite positive descriptions and you make them seem negative. What would be a positive score according to you? Removing the ability to configure the phone in the other direction? Seems like a negative to me.

So yeah, I would suggest changing the score representation since it seems misleading at the moment.

**Comment by petrnalevka** [comment]
Many thanks for your feedback. In fact we are getting surprisingly many support request from angry people who's alarms or background services do not work and after a lot of effort on debugging we find out that they simply turned the background restrictions ON - not even knowing why. 

So the question is should there be an option evil option to break normal functionality off apps in the first place. Even when this option would be all RED and users will be warned "only press this when you know what you are doing" still users will keep enabling it. Maybe it should be called "Break the app's core functionality" - because this is exactly what it is doing.  

IMHO this option is unnecessary and evil. After all you can always uninstall the app if it is consuming too much battery. Nowadays for any app category there are dozen alternatives - you can choose the best app which does not consume unnecessary resources. 

Most user do not even know what background processes mean and even for me as programmer is hard to assume what features of an app would be broken and what would keep work if I would enable such option. 

So IMHO this option should not exists in the system. Why did Google implement it? Maybe because they still try somehow standardize the battery management on Android and they hope this option will keep more vendors from modifying the OS? But as in the other cases as with doze mode this won't be the case IMHO..
